# Ryu SDN Framework
#
# VERSION 0.0.1

FROM ubuntu:16.04

ENV HOME /root
WORKDIR /root

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    python-setuptools \
    python-pip \
    python-eventlet \
    python-lxml \
    python-msgpack \
    iproute2 

RUN rm -rf /var/lib/apt/lists/* \
    && curl -kL https://github.com/osrg/ryu/archive/v4.31.tar.gz | tar -xvz \
    && mv ryu-* ryu \
    && cd ryu \
    && pip install -r tools/pip-requires \
    && pip install tinyrpc==1.0.1  \
    && python setup.py install